manifest:
  version: 0.8

  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: zephyr-v3.3.0
      import:
        file: west.yml
        path-prefix: deps
        name-allowlist:
          - cmsis
          - hal_nordic
          - nrfxlib
    - name: golioth
      path: modules/lib/golioth
      revision: ff8de0da412680d8c8e3ca082369fda2f71a99ad
      url: https://github.com/golioth/golioth-zephyr-sdk.git
      import:
        file: west-external.yml
        path-prefix: deps

  self:
    path: app
